## Testing accuracy of RF Classifier for Unloaded IM Electrical faults, testing and training at 7 different rotational speeds

In [1]:
from jupyterthemes import get_themes
import jupyterthemes as jt
from jupyterthemes.stylefx import set_nb_theme

set_nb_theme('chesterish')

In [2]:
import pandas as pd

### Importing Training Data

In [3]:
data_10=pd.read_csv(r'D:\Acads\BTP\final\Train_10hz.csv')
data_20=pd.read_csv(r'D:\Acads\BTP\final\Train_20hz.csv')
data_30=pd.read_csv(r'D:\Acads\BTP\final\Train_30Hz.csv')
data_15=pd.read_csv(r'D:\Acads\BTP\final\Train_15hz.csv')
data_25=pd.read_csv(r'D:\Acads\BTP\final\Train_25hz.csv')
data_35=pd.read_csv(r'D:\Acads\BTP\final\Train_35Hz.csv')
data_40=pd.read_csv(r'D:\Acads\BTP\final\Train_40Hz.csv')

In [4]:
data_10.head

<bound method NDFrame.head of        X_Value  Acceleration  Acceleration_0  Acceleration_1   Voltage  \
0      0.00000     -0.894914        1.137409       -0.090584  0.180869   
1      0.00005     -0.850783        1.032799       -0.298761  0.187243   
2      0.00010     -0.823247        0.772751       -0.332824  0.181048   
3      0.00015     -0.446593        0.686682       -0.477653  0.186483   
4      0.00020     -0.287769        0.458924       -0.312852  0.181477   
...        ...           ...             ...             ...       ...   
69991  0.49975     -1.312012        0.070079       -1.130611 -0.206765   
69992  0.49980     -0.593247        0.854768       -0.124157 -0.208153   
69993  0.49985     -1.294310        0.090092       -0.714012 -0.207306   
69994  0.49990     -0.549239        0.662740        0.230809 -0.208594   
69995  0.49995     -1.545822       -0.584710       -0.772091 -0.208061   

       Voltage_0  Voltage_1  Voltage_2  Comment  
0      -0.000696  -0.180753  -0

### Importing Testing Data

In [5]:
test_10=pd.read_csv(r'D:\Acads\BTP\final\Test_10hz.csv')
test_20=pd.read_csv(r'D:\Acads\BTP\final\Test_20hz.csv')
test_30=pd.read_csv(r'D:\Acads\BTP\final\Test_30hz.csv')
test_15=pd.read_csv(r'D:\Acads\BTP\final\Test_15hz.csv')
test_25=pd.read_csv(r'D:\Acads\BTP\final\Test_25hz.csv')
test_35=pd.read_csv(r'D:\Acads\BTP\final\Test_35hz.csv')
test_40=pd.read_csv(r'D:\Acads\BTP\final\Test_40hz.csv')

In [6]:
test_25.head

<bound method NDFrame.head of         X_Value  Acceleration  Acceleration_0  Acceleration_1   Voltage  \
0       4.99990      1.500475        1.040781       -1.022173 -0.110060   
1       4.99995      4.719365        1.540128       -1.912347 -0.111178   
2       5.00000      5.454724        1.156808       -2.523154 -0.107449   
3       5.00005      7.233873        3.343404        0.381887 -0.108173   
4       5.00010      5.668374        3.503264        2.171425 -0.104477   
...         ...           ...             ...             ...       ...   
169981  0.99925     -0.239950       -2.320210        5.937723  0.041256   
169982  0.99930     -1.446988       -2.470616        4.027863  0.039603   
169983  0.99935     -3.087594       -2.481667       -0.548966  0.038046   
169984  0.99940     -3.809432       -2.131251       -7.430442  0.035548   
169985  0.99945     -6.236292       -4.082968      -10.095081  0.034613   

        Voltage_0  Voltage_1  Voltage_2  Comment  
0        0.227364 

### Assigning X and y for Testing

In [7]:
dataset_test_10 = test_10.values
X_test_10 = dataset_test_10[:,0:8]
print(X_test_10)

y_test_10= dataset_test_10[:,8]
print(y_test_10)

[[ 5.000000e+00 -8.344330e-01  7.829420e-01 ... -2.060260e-01
   1.365140e-01 -2.780000e-04]
 [ 5.000050e+00 -1.074513e+00  5.448700e-01 ... -2.130990e-01
   1.434710e-01 -2.400000e-04]
 [ 5.000100e+00 -7.946040e-01  8.722030e-01 ... -2.064670e-01
   1.376380e-01 -2.630000e-04]
 ...
 [ 1.029985e+01 -6.888860e-01 -8.135720e-01 ... -1.275750e-01
  -8.762700e-02  3.890000e-04]
 [ 1.029990e+01 -1.729847e+00 -1.517226e+00 ... -1.235950e-01
  -8.622200e-02  4.010000e-04]
 [ 1.029995e+01 -1.054599e+00 -4.145350e-01 ... -1.291380e-01
  -8.604400e-02  3.930000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [8]:
dataset_test_15 = test_15.values
X_test_15 = dataset_test_15[:,0:8]
print(X_test_15)

y_test_15= dataset_test_15[:,8]
print(y_test_15)

[[ 4.999900e+00 -4.773250e-01 -1.187070e+00 ... -5.741700e-02
  -1.498020e-01 -2.540000e-04]
 [ 4.999950e+00 -1.584668e+00 -1.393218e+00 ... -6.057300e-02
  -1.510910e-01 -2.510000e-04]
 [ 5.000000e+00 -7.706330e-01 -3.107870e-01 ... -5.920600e-02
  -1.488900e-01 -2.340000e-04]
 ...
 [ 9.994000e-01  2.225080e-01 -2.440044e+00 ...  1.872560e-01
  -2.161080e-01  2.770000e-04]
 [ 9.994500e-01  9.270120e-01 -2.612428e+00 ...  1.821630e-01
  -2.074120e-01  2.670000e-04]
 [ 9.995000e-01  1.049941e+00 -2.858725e+00 ...  1.870790e-01
  -2.171580e-01  2.270000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [9]:
dataset_test_20 = test_20.values
X_test_20 = dataset_test_20[:,0:8]
print(X_test_20)

y_test_20= dataset_test_20[:,8]
print(y_test_20)

[[ 4.999950e+00  1.432250e+00 -7.591800e-01 ...  1.648070e-01
  -2.134080e-01 -3.090000e-04]
 [ 5.000000e+00  1.590828e+00 -1.022422e+00 ...  1.584680e-01
  -2.096290e-01 -2.370000e-04]
 [ 5.000050e+00  3.676314e+00  8.419990e-01 ...  1.606730e-01
  -2.150380e-01 -3.100000e-04]
 ...
 [ 9.994000e-01  2.225080e-01 -2.440044e+00 ...  1.872560e-01
  -2.161080e-01  2.770000e-04]
 [ 9.994500e-01  9.270120e-01 -2.612428e+00 ...  1.821630e-01
  -2.074120e-01  2.670000e-04]
 [ 9.995000e-01  1.049941e+00 -2.858725e+00 ...  1.870790e-01
  -2.171580e-01  2.270000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [10]:
dataset_test_25 = test_25.values
X_test_25 = dataset_test_25[:,0:8]
print(X_test_25)

y_test_25= dataset_test_25[:,8]
print(y_test_25)

[[ 4.999900e+00  1.500475e+00  1.040781e+00 ...  2.273640e-01
  -1.198740e-01 -3.230000e-04]
 [ 4.999950e+00  4.719365e+00  1.540128e+00 ...  2.220230e-01
  -1.120500e-01 -3.360000e-04]
 [ 5.000000e+00  5.454724e+00  1.156808e+00 ...  2.283640e-01
  -1.229030e-01 -3.010000e-04]
 ...
 [ 9.993500e-01 -3.087594e+00 -2.481667e+00 ... -2.220700e-01
   1.849030e-01  2.530000e-04]
 [ 9.994000e-01 -3.809432e+00 -2.131251e+00 ... -2.252800e-01
   1.885530e-01  2.810000e-04]
 [ 9.994500e-01 -6.236292e+00 -4.082968e+00 ... -2.205110e-01
   1.871130e-01  2.810000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [11]:
dataset_test_30 = test_30.values
X_test_30 = dataset_test_30[:,0:8]
print(X_test_30)

y_test_30= dataset_test_30[:,8]
print(y_test_30)

[[ 9.999900e+00 -2.836451e+00  2.134860e-01 ...  1.390050e-01
  -2.181810e-01 -3.410000e-04]
 [ 9.999950e+00 -5.756680e-01  1.183205e+00 ...  1.409670e-01
  -2.312950e-01 -3.700000e-04]
 [ 1.000000e+01 -5.429690e-01  3.190770e-01 ...  1.349120e-01
  -2.188170e-01 -3.820000e-04]
 ...
 [ 9.993500e-01 -8.511520e-01  2.595058e+00 ...  6.482000e-02
   1.679310e-01  5.870000e-05]
 [ 9.994000e-01 -5.942310e-01  1.314704e+00 ...  5.725800e-02
   1.619690e-01  5.360000e-05]
 [ 9.994500e-01  2.053163e+00  1.665364e+00 ...  6.957000e-02
   1.648340e-01  7.660000e-05]]
[1. 1. 1. ... 0. 0. 0.]


In [12]:
dataset_test_35 = test_35.values
X_test_35 = dataset_test_35[:,0:8]
print(X_test_35)

y_test_35= dataset_test_35[:,8]
print(y_test_35)

[[ 4.999950e+00 -2.035448e+00  1.851377e+00 ... -2.271250e-01
   1.600200e-01 -5.510000e-04]
 [ 5.000000e+00 -1.433280e-01  6.595470e-01 ... -2.197150e-01
   1.503190e-01 -5.180000e-04]
 [ 5.000050e+00  3.612940e-01 -1.616187e+00 ... -2.267110e-01
   1.645300e-01 -6.000000e-04]
 ...
 [ 9.998500e-01  2.955091e+00  5.106530e+00 ... -1.001870e-01
   2.655450e-01  3.080000e-04]
 [ 9.999000e-01  4.914576e+00  4.976874e+00 ... -1.027140e-01
   2.601870e-01  2.830000e-04]
 [ 9.999500e-01  3.984865e+00  3.885970e+00 ... -9.585400e-02
   2.653690e-01  2.670000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [13]:
dataset_test_40 = test_40.values
X_test_40 = dataset_test_40[:,0:8]
print(X_test_40)

y_test_40= dataset_test_40[:,8]
print(y_test_40)

[[ 4.999950e+00 -3.690069e+00  3.705851e+00 ...  3.635800e-02
  -2.213240e-01 -3.540000e-04]
 [ 5.000000e+00 -6.458301e+00  4.262906e+00 ...  3.789900e-02
  -2.149020e-01 -3.770000e-04]
 [ 5.000050e+00 -5.995228e+00  5.611772e+00 ...  3.146900e-02
  -2.188980e-01 -3.430000e-04]
 ...
 [ 1.789985e+01  2.116103e+00  1.529692e+00 ... -2.290250e-01
   9.649200e-02  4.340000e-05]
 [ 1.789990e+01  2.853552e+00 -2.818100e-01 ... -2.351160e-01
   1.077650e-01  7.790000e-05]
 [ 1.789995e+01  1.218354e+00 -3.233696e+00 ... -2.338800e-01
   1.050610e-01  1.240000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [17]:
import sklearn as sk
import numpy as np

### 10Hz Training and Testing

In [7]:
dataset_10=data_10.values
X_10= dataset_10[:,0:8]
print(X_10)
y_10=dataset_10[:,8]
print(y_10)

[[ 0.000000e+00 -8.949140e-01  1.137409e+00 ... -6.960000e-04
  -1.807530e-01 -1.200000e-04]
 [ 5.000000e-05 -8.507830e-01  1.032799e+00 ... -3.747000e-03
  -1.853790e-01 -9.450000e-05]
 [ 1.000000e-04 -8.232470e-01  7.727510e-01 ... -2.323000e-03
  -1.800260e-01 -1.430000e-04]
 ...
 [ 4.998500e-01 -1.294310e+00  9.009200e-02 ...  2.856300e-02
   1.796260e-01  9.060000e-05]
 [ 4.999000e-01 -5.492390e-01  6.627400e-01 ...  2.936200e-02
   1.789270e-01  8.300000e-05]
 [ 4.999500e-01 -1.545822e+00 -5.847100e-01 ...  2.959900e-02
   1.786610e-01  5.360000e-05]]
[1. 1. 1. ... 0. 0. 0.]


In [8]:
from sklearn.ensemble import RandomForestClassifier
rf_10 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_10.fit(X_10, y_10);

In [28]:
predictions_10 = rf_10.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 10Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 10Hz: 0.551 degrees.
Accuracy: 99.449 %.


In [29]:
predictions_15 = rf_10.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 10Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 10Hz: 0.9 degrees.
Accuracy: 99.1 %.


In [30]:
predictions_20 = rf_10.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 10Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 10Hz: 0.83 degrees.
Accuracy: 99.17 %.


In [41]:
predictions_25 = rf_10.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 10Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 10Hz: 0.91 degrees.
Accuracy: 99.09 %.


In [35]:
predictions_30 = rf_10.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 10Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 10Hz: 0.975 degrees.
Accuracy: 99.025 %.


In [36]:
predictions_35 = rf_10.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 10Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 10Hz: 1.104 degrees.
Accuracy: 98.896 %.


In [37]:
predictions_40 = rf_10.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 10Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 10Hz: 1.177 degrees.
Accuracy: 98.823 %.


### 15Hz Testing and Training

In [15]:
dataset_15=data_15.values
X_15= dataset_15[:,0:8]
print(X_15)
y_15=dataset_15[:,8]
print(y_15)

[[ 0.000000e+00  1.402680e-01 -1.676841e+00 ...  2.147770e-01
  -2.062800e-01 -5.400000e-04]
 [ 5.000000e-05  5.803530e-01 -1.096458e+00 ...  2.119730e-01
  -2.011490e-01 -5.650000e-04]
 [ 1.000000e-04 -4.285230e-01 -2.326594e+00 ...  2.136540e-01
  -2.075150e-01 -5.860000e-04]
 ...
 [ 1.689985e+01  5.131110e-01 -2.421700e-02 ...  1.020180e-01
   1.153490e-01  2.950000e-04]
 [ 1.689990e+01  3.504200e-02 -9.087270e-01 ...  9.533700e-02
   1.138810e-01  2.640000e-04]
 [ 1.689995e+01  9.777820e-01 -5.863050e-01 ...  1.052410e-01
   1.137720e-01  2.510000e-04]]
[1. 1. 1. ... 0. 0. 0.]


In [16]:
from sklearn.ensemble import RandomForestClassifier
rf_15 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_15.fit(X_15, y_15);

In [18]:
predictions_10 = rf_15.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 15Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 15Hz: 0.777 degrees.
Accuracy: 99.223 %.


In [19]:
predictions_15 = rf_15.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 15Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 15Hz: 0.426 degrees.
Accuracy: 99.574 %.


In [20]:
predictions_20 = rf_15.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 15Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 15Hz: 0.893 degrees.
Accuracy: 99.107 %.


In [21]:
predictions_25 = rf_15.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 15Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 15Hz: 1.221 degrees.
Accuracy: 98.779 %.


In [22]:
predictions_30 = rf_15.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 15Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 15Hz: 1.749 degrees.
Accuracy: 98.251 %.


In [23]:
predictions_35 = rf_15.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 15Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 15Hz: 1.303 degrees.
Accuracy: 98.697 %.


In [24]:
predictions_40 = rf_15.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 15Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 15Hz: 1.629 degrees.
Accuracy: 98.371 %.


### 20Hz Testing and Training

In [ ]:
dataset_20=data_20.values
X_20= dataset_20[:,0:9]
print(X_20)
y_20=dataset_20[:,9]
print(y_20)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_20 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_20.fit(X_20, y_20);

In [ ]:
predictions_10 = rf_20.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 20Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_15 = rf_20.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 20Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_20.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 20Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_25 = rf_20.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 20Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_30 = rf_20.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 20Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_35 = rf_20.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 20Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_40 = rf_20.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 20Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

### 25Hz Testing and Training

In [ ]:
dataset_25=data_25.values
X_25= dataset_25[:,0:9]
print(X_25)
y_25=dataset_25[:,9]
print(y_25)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_25 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_25.fit(X_25, y_25);

In [ ]:
predictions_10 = rf_25.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 25Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_15 = rf_25.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 25Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_25.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 25Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_25 = rf_25.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 25Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_30 = rf_25.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 25Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_35 = rf_25.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 25Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_40 = rf_25.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 25Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

### 30Hz Testing and Training

In [ ]:
dataset_30=data_30.values
X_30= dataset_30[:,0:8]
print(X_30)
y_30=dataset_30[:,8]
print(y_30)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_30 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_30.fit(X_30, y_30);

In [ ]:
predictions_10 = rf_30.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 30Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_15 = rf_30.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 30Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_30.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 30Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_25 = rf_30.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 30Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_30 = rf_30.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 30Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_35 = rf_30.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 30Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_40 = rf_30.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 30Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

### 35Hz Training and Testing

In [ ]:
dataset_35=data_35.values
X_35= dataset_35[:,0:8]
print(X_35)
y_35=dataset_35[:,8]
print(y_35)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_35 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_35.fit(X_35, y_35);

In [ ]:
predictions_10 = rf_35.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 35Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_15 = rf_35.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 35Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_25 = rf_35.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 35Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_30 = rf_35.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 35Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_35 = rf_35.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 35Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_40 = rf_35.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 35Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

### 40Hz Training and Testing

In [ ]:
dataset_40=data_40.values
X_40= dataset_40[:,0:9]
print(X_40)
y_40=dataset_40[:,9]
print(y_40)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_40 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_40.fit(X_40, y_40);

In [ ]:
predictions_10 = rf_35.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 35Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_15 = rf_35.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 35Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_25 = rf_35.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 35Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_30 = rf_35.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 35Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_35 = rf_35.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 35Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

In [ ]:
predictions_40 = rf_35.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 35Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')