### Testing accuracy of RF classifier for lightly loaded, testing and training with all the rotational speeds

In [111]:
from jupyterthemes import get_themes
import jupyterthemes as jt
from jupyterthemes.stylefx import set_nb_theme

set_nb_theme('chesterish')

In [1]:
import pandas as pd

In [31]:
data_10=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train10hz.csv')
data_20=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train20hz.csv')
data_30=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train30Hz.csv')
data_15=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train15hz.csv')
data_25=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train25hz.csv')
data_35=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train35Hz.csv')
data_40=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Train40Hz.csv')

In [32]:
data_10=data_10.head(44990)
data_15=data_15.head(44990)
data_20=data_20.head(44990)
data_25=data_25.head(44990)
data_30=data_30.head(44990)
data_35=data_35.head(44990)
data_40=data_40.head(44990)

In [33]:
data_25.head

<bound method NDFrame.head of         X_Value  Acceleration  Acceleration_0  Acceleration_1   Voltage  \
0       0.99995     -7.163913       -9.133048        1.168647  0.219481   
1       1.00005     -5.477944       -5.267799        8.494781  0.219536   
2       1.00010     -5.192873       -3.597126        4.677267  0.215034   
3       1.00015     -6.456089       -0.642539       -0.714869  0.219319   
4       1.00020     -7.560112       -0.160380       -0.901849  0.215302   
...         ...           ...             ...             ...       ...   
44985  22.97005     -1.170275       -5.775373       -1.842627  0.050912   
44986  22.97010     -0.653728       -5.076016       -1.247748  0.048153   
44987  22.97015     -0.420655       -4.634989        0.005724  0.047445   
44988  22.97020      0.454597       -3.451386        0.844312  0.045144   
44989  22.97025      1.315959       -2.316281       -0.131508  0.043801   

       Voltage_0  Voltage_1  Voltage_2  Voltage_3  Comment  
0      -

In [34]:
#shuffling
data_20=data_20.sample(frac=1)
data_30=data_30.sample(frac=1)
data_40=data_40.sample(frac=1)
data_10=data_10.sample(frac=1)
data_15=data_15.sample(frac=1)
data_25=data_25.sample(frac=1)
data_35=data_35.sample(frac=1)

In [35]:
data_25.head

<bound method NDFrame.head of         X_Value  Acceleration  Acceleration_0  Acceleration_1   Voltage  \
40733  22.75740     -2.638782        0.519209       -1.945061  0.182213   
2378    1.11890     -3.451955      -11.227927        5.861755  0.209678   
23663   1.18315      2.612612       -5.028132        0.759768 -0.139489   
5335    1.01685     -4.220137       -3.469803        1.502907 -0.241704   
7508    1.12550      2.645188        2.071522        2.991022  0.070474   
...         ...           ...             ...             ...       ...   
27006  12.53925     -5.076091       -0.636399      -13.607622  0.113960   
9918    1.24600      2.956074        2.087360       -4.552357  0.023133   
26603  12.51910      1.053260        7.363848       -9.532182 -0.108357   
38690  22.90590     -2.719546        6.833436        3.104239  0.218772   
11093   1.05485      4.644624        0.929541       -0.160058  0.101547   

       Voltage_0  Voltage_1  Voltage_2  Voltage_3  Comment  
40733   

In [25]:
import sklearn as sk

### Assigning X and y for training

In [36]:
dataset_10=data_10.values
X_10= dataset_10[:,0:9]
print(X_10)
y_10=dataset_10[:,9]
print(y_10)

[[ 5.085000e+00 -1.707228e+00  6.246600e-02 ...  1.432430e-01
  -3.060000e-04  5.167400e-02]
 [ 1.129900e+00 -2.264587e+00 -2.125112e+00 ...  9.209500e-02
  -5.230000e-04  7.830000e-03]
 [ 9.996950e+00  2.665160e-01 -6.387330e-01 ... -1.365330e-01
  -5.360000e-04 -2.994500e-02]
 ...
 [ 1.207200e+00 -9.250320e-01 -1.818652e+00 ... -1.519890e-01
  -1.390000e-04  6.438000e-03]
 [ 1.065600e+00 -2.914142e+00 -2.603219e+00 ...  2.164220e-01
  -3.250000e-04  5.515400e-02]
 [ 2.662200e+00 -3.081750e-01 -2.236965e+00 ... -3.668300e-02
  -4.300000e-04 -7.643100e-02]]
[2. 0. 3. ... 2. 2. 1.]


In [37]:
dataset_15=data_15.values
X_15= dataset_15[:,0:9]
print(X_15)
y_15=dataset_15[:,9]
print(y_15)

[[ 1.206950e+00  5.416310e-01  7.948510e-01 ... -2.216420e-01
  -1.065000e-03  2.374000e-03]
 [ 9.973550e+00 -6.526800e-02  7.123430e-01 ...  1.843410e-01
   2.543000e-03 -2.515200e-02]
 [ 1.241700e+00  6.011280e-01 -1.698450e+00 ...  2.108030e-01
  -5.020000e-04 -4.509600e-02]
 ...
 [ 1.139700e+00  3.278570e-01  2.858298e+00 ... -2.113930e-01
   1.490000e-03 -1.438000e-03]
 [ 1.179350e+00 -1.784796e+00  1.856288e+00 ...  1.607360e-01
  -3.800000e-04 -7.120300e-02]
 [ 1.168300e+00  4.705228e+00  9.671000e-03 ...  5.926900e-02
  -3.060000e-04 -3.767500e-02]]
[0. 0. 0. ... 3. 3. 1.]


In [38]:
dataset_20=data_20.values
X_20= dataset_20[:,0:9]
print(X_20)
y_20=dataset_20[:,9]
print(y_20)

[[ 1.2344500e+00 -3.4222600e-01 -4.5284300e-01 ...  7.0553000e-02
  -4.6000000e-04  1.0201200e-01]
 [ 1.2510950e+01  1.0227740e+00  1.0982410e+00 ...  1.2791800e-01
  -9.5900000e-04  1.2842100e-01]
 [ 1.0294500e+00 -1.2169200e-01 -1.3180258e+01 ...  2.0500300e-01
  -2.8700000e-04  3.9176000e-02]
 ...
 [ 1.2101500e+00  1.5878780e+00  2.4058520e+00 ... -6.1962000e-02
   1.4540000e-03  7.1056000e-02]
 [ 1.0334500e+00 -3.0818170e+00  3.7764400e-01 ...  1.5896200e-01
  -1.1900000e-03 -1.7939000e-02]
 [ 2.6943500e+00 -3.0298180e+00 -3.0449830e+00 ...  1.2097300e-01
   7.6700000e-04  1.9543100e-01]]
[4. 3. 1. ... 4. 3. 1.]


In [39]:
dataset_25=data_25.values
X_25= dataset_25[:,0:9]
print(X_25)
y_25=dataset_25[:,9]
print(y_25)

[[ 2.2757400e+01 -2.6387820e+00  5.1920900e-01 ... -2.3064200e-01
  -1.1050000e-03 -4.2601000e-02]
 [ 1.1189000e+00 -3.4519550e+00 -1.1227927e+01 ... -1.8113800e-01
  -2.0800000e-04  1.5830300e-01]
 [ 1.1831500e+00  2.6126120e+00 -5.0281320e+00 ...  2.2829500e-01
  -6.1000000e-04 -1.2593200e-01]
 ...
 [ 1.2519100e+01  1.0532600e+00  7.3638480e+00 ...  2.3148800e-01
   7.6600000e-04  4.1550000e-03]
 [ 2.2905900e+01 -2.7195460e+00  6.8334360e+00 ... -1.9495600e-01
  -5.7900000e-04  8.7372000e-02]
 [ 1.0548500e+00  4.6446240e+00  9.2954100e-01 ... -2.4461200e-01
   2.2570000e-03  3.7807000e-02]]
[3. 1. 4. ... 1. 0. 0.]


In [40]:
dataset_30=data_30.values
X_30= dataset_30[:,0:9]
print(X_30)
y_30=dataset_30[:,9]
print(y_30)

[[ 2.5115500e+00 -5.7290880e+00 -1.3638740e+00 ...  4.0533000e-02
  -4.6800000e-04 -6.3050000e-03]
 [ 1.0827000e+00 -2.6000600e+00  2.5565040e+00 ... -1.6953300e-01
   2.7490000e-03 -2.3015700e-01]
 [ 2.6536000e+00  1.3286210e+00  7.9533000e-02 ... -2.3207200e-01
  -4.3400000e-04 -2.1344000e-02]
 ...
 [ 1.2654450e+01 -6.8439290e+00  2.7389400e-01 ...  1.3921700e-01
  -6.8300000e-04 -2.5010700e-01]
 [ 1.1869000e+00  1.4193420e+00  1.5044621e+01 ... -3.4181000e-02
  -2.7100000e-04  1.8717000e-02]
 [ 1.0338500e+00 -2.9479470e+00  1.9802960e+00 ... -1.3068600e-01
  -4.8800000e-04  7.1684000e-02]]
[2. 0. 2. ... 0. 1. 4.]


In [41]:
dataset_35=data_35.values
X_35= dataset_35[:,0:9]
print(X_35)
y_35=dataset_35[:,9]
print(y_35)

[[ 1.182350e+00  4.193967e+00  4.230983e+00 ... -1.793500e-01
  -2.580000e-04 -2.314590e-01]
 [ 1.168200e+00  2.092992e+00  7.382878e+00 ...  1.138160e-01
  -3.820000e-04 -6.749700e-02]
 [ 1.243150e+00  6.022350e-01 -1.963901e+00 ... -2.342570e-01
   9.590000e-04  1.766870e-01]
 ...
 [ 1.267945e+01 -2.644560e+00 -4.413020e-01 ...  2.186320e-01
  -7.810000e-04  2.516990e-01]
 [ 2.729550e+00 -4.012142e+00 -1.812881e+00 ...  4.241100e-02
   8.560000e-04 -9.895400e-02]
 [ 1.060250e+00 -4.106551e+00 -5.288917e+00 ... -2.001160e-01
  -2.630000e-04  3.047600e-02]]
[2. 1. 2. ... 0. 1. 1.]


In [42]:
dataset_40=data_40.values
X_40= dataset_40[:,0:9]
print(X_40)
y_40=dataset_40[:,9]
print(y_40)

[[ 1.027550e+00  4.547200e-01  7.451636e+00 ... -2.186170e-01
   8.330000e-04 -1.628680e-01]
 [ 1.026400e+00  1.122346e+00 -1.123838e+00 ...  9.845900e-02
  -9.220000e-04 -1.297100e-02]
 [ 4.594950e+00 -3.482196e+00 -5.994413e+00 ...  3.765800e-02
   3.358000e-03 -1.788950e-01]
 ...
 [ 1.244615e+01  4.545544e+00 -8.181009e+00 ...  6.341400e-02
  -2.480000e-04 -2.883800e-02]
 [ 1.153700e+00 -1.391793e+00 -1.089951e+00 ...  2.341350e-01
  -9.450000e-04 -4.838600e-02]
 [ 1.222200e+00 -6.719402e+00 -4.400356e+00 ...  2.135660e-01
  -5.040000e-04  6.016100e-02]]
[1. 0. 3. ... 1. 0. 2.]


### Training Random Forest Classifier

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf_10 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_10.fit(X_10, y_10);

In [44]:
from sklearn.ensemble import RandomForestClassifier
rf_15 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_15.fit(X_15, y_15);

In [45]:
from sklearn.ensemble import RandomForestClassifier
rf_20 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_20.fit(X_20, y_20);

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf_25 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_25.fit(X_25, y_25);

In [47]:
from sklearn.ensemble import RandomForestClassifier
rf_30 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_30.fit(X_30, y_30);

In [48]:
from sklearn.ensemble import RandomForestClassifier
rf_35 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_35.fit(X_35, y_35);

In [49]:
from sklearn.ensemble import RandomForestClassifier
rf_40 = RandomForestClassifier(n_estimators = 1000, random_state = 42)
rf_40.fit(X_40, y_40);

### Importing Testing data

In [50]:
test_10=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test10hz.csv')
test_20=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test20hz.csv')
test_30=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test30Hz.csv')
test_15=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test15hz.csv')
test_25=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test25hz.csv')
test_35=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test35Hz.csv')
test_40=pd.read_csv(r'D:\Acads\BTP\Lightly Loaded\Test40Hz.csv')

In [51]:
test_10=test_10.head(99990)
test_15=test_15.head(99990)
test_20=test_20.head(99990)
test_25=test_25.head(99990)
test_30=test_30.head(99990)
test_35=test_35.head(99990)
test_40=test_40.head(99990)

In [52]:
#shuffling
test_20=test_20.sample(frac=1)
test_30=test_30.sample(frac=1)
test_40=test_40.sample(frac=1)
test_10=test_10.sample(frac=1)
test_15=test_15.sample(frac=1)
test_25=test_25.sample(frac=1)
test_35=test_35.sample(frac=1)

### Assigning X and y for testing

In [53]:
dataset_test_10 = test_10.values
X_test_10 = dataset_test_10[:,0:9]
print(X_test_10)

y_test_10= dataset_test_10[:,9]
print(y_test_10)

[[ 5.242000e-01  2.735230e-01  5.153800e-02 ... -3.137600e-02
   2.073000e-03  7.139000e-03]
 [ 7.577000e-01 -8.405800e-01 -1.463571e+00 ...  2.037150e-01
  -5.350000e-04  7.330000e-04]
 [ 5.345000e-02 -3.146200e-02 -2.847552e+00 ...  2.079200e-02
  -5.130000e-04 -5.458500e-02]
 ...
 [ 7.888500e-01 -8.252140e-01 -1.401322e+00 ...  5.255300e-02
   1.126000e-03 -3.020900e-02]
 [ 8.341000e-01 -1.718906e+00 -4.401970e-01 ...  2.091240e-01
  -3.000000e-04 -2.487700e-02]
 [ 7.106500e-01  1.508589e+00 -6.054590e-01 ... -1.643150e-01
  -2.580000e-04  1.386500e-02]]
[0. 3. 1. ... 2. 1. 0.]


In [54]:
dataset_test_15 = test_15.values
X_test_15 = dataset_test_15[:,0:9]
print(X_test_15)

y_test_15= dataset_test_15[:,9]
print(y_test_15)

[[ 9.310000e-02  1.191432e+00  1.065951e+00 ... -6.482000e-02
   1.253000e-03 -1.111800e-01]
 [ 5.108000e-01 -8.521350e-01  6.375690e-01 ...  2.166050e-01
  -8.960000e-04 -5.141000e-03]
 [ 8.508000e-01  2.587903e+00 -3.101339e+00 ...  2.075780e-01
  -1.220000e-03  4.961800e-02]
 ...
 [ 1.078500e-01 -5.073200e-01 -7.300810e-01 ...  2.120510e-01
   9.840000e-04 -2.735700e-02]
 [ 9.747000e-01 -1.268126e+00 -2.169436e+00 ...  2.234050e-01
  -4.520000e-04  1.972200e-02]
 [ 7.856500e-01  7.555270e-01  6.087160e-01 ...  1.548390e-01
  -3.380000e-04 -4.104100e-02]]
[2. 3. 0. ... 2. 2. 2.]


In [55]:
dataset_test_20 = test_20.values
X_test_20 = dataset_test_20[:,0:9]
print(X_test_20)

y_test_20= dataset_test_20[:,9]
print(y_test_20)

[[ 5.245500e-01  4.036741e+00  1.846343e+00 ...  2.204160e-01
  -4.600000e-04  8.449700e-02]
 [ 8.379500e-01 -6.125470e-01 -9.297220e-01 ...  7.865200e-02
  -8.400000e-04  9.840000e-03]
 [ 5.791500e-01 -3.755344e+00 -2.086191e+00 ...  2.168840e-01
  -4.910000e-04 -1.639200e-02]
 ...
 [ 7.150000e-01 -6.048020e-01 -4.252896e+00 ... -9.831000e-03
  -1.211000e-03 -9.982600e-02]
 [ 2.557500e-01 -2.465699e+00 -2.071457e+00 ... -2.322560e-01
  -9.590000e-04 -9.629000e-02]
 [ 4.954000e-01 -1.780002e+00 -2.858970e+00 ... -1.081930e-01
   2.446000e-03  7.495700e-02]]
[2. 3. 2. ... 3. 3. 3.]


In [56]:
dataset_test_25 = test_25.values
X_test_25 = dataset_test_25[:,0:9]
print(X_test_25)

y_test_25= dataset_test_25[:,9]
print(y_test_25)

[[ 9.400500e-01 -8.020111e+00 -5.245944e+00 ...  1.828050e-01
  -3.550000e-04  4.339500e-02]
 [ 3.325000e-02 -6.542999e+00 -2.229844e+00 ... -2.195170e-01
  -2.940000e-04 -1.188540e-01]
 [ 4.270500e-01 -9.489400e-02 -4.414844e+00 ...  1.941880e-01
   1.389000e-03 -8.942800e-02]
 ...
 [ 3.215000e-02 -4.435878e+00 -6.415550e+00 ... -7.151500e-02
  -2.630000e-04 -4.566600e-02]
 [ 4.624000e-01 -3.592586e+00 -2.097241e+00 ... -6.214300e-02
   2.769000e-03 -1.469430e-01]
 [ 1.494000e-01  2.939602e+00  4.161735e+00 ...  1.523630e-01
  -5.350000e-04  2.117000e-02]]
[1. 2. 4. ... 1. 3. 4.]


In [57]:
dataset_test_30 = test_30.values
X_test_30 = dataset_test_30[:,0:9]
print(X_test_30)

y_test_30= dataset_test_30[:,9]
print(y_test_30)

[[ 4.211500e-01  3.280975e+00  1.756467e+00 ... -8.645000e-03
  -3.680000e-04 -2.126710e-01]
 [ 2.559500e-01  4.166800e+00  6.938782e+00 ... -8.604600e-02
  -3.140000e-04  2.275240e-01]
 [ 4.722500e-01 -6.410660e-01  1.192537e+00 ...  1.517400e-01
   3.165000e-03 -1.712610e-01]
 ...
 [ 7.096500e-01  6.644675e+00  5.647009e+00 ...  1.723670e-01
  -5.360000e-04 -5.488900e-02]
 [ 3.110000e-02 -7.973399e+00 -1.703239e+00 ...  5.423400e-02
  -8.640000e-04  1.334950e-01]
 [ 9.180000e-01 -3.079290e-01 -5.772917e+00 ...  3.031000e-03
   3.446000e-03 -1.058300e-01]]
[4. 1. 3. ... 2. 0. 3.]


In [58]:
dataset_test_35 = test_35.values
X_test_35 = dataset_test_35[:,0:9]
print(X_test_35)

y_test_35= dataset_test_35[:,9]
print(y_test_35)

[[ 1.9210000e-01  9.9652270e+00  7.4246240e+00 ... -2.5363300e-01
   1.1190000e-03 -1.6205800e-01]
 [ 5.1065000e-01 -6.3516600e-01 -7.4485020e+00 ... -1.2424600e-01
  -3.1800000e-04 -7.2538000e-02]
 [ 8.3700000e-02 -3.6407740e+00  3.1929980e+00 ... -1.5626000e-02
  -3.9100000e-04  8.4166000e-02]
 ...
 [ 3.3370000e-01  4.0451010e+00  1.4296260e+00 ...  1.7250900e-01
  -1.4720000e-03 -1.8749000e-01]
 [ 9.6190000e-01  2.1382300e+00  1.5793581e+01 ...  2.5179800e-01
   8.9700000e-04 -1.1528000e-02]
 [ 1.2235000e-01  7.4616600e+00  3.8102150e+00 ... -4.5536000e-02
  -2.8300000e-04  3.7073000e-02]]
[4. 4. 4. ... 3. 1. 2.]


In [59]:
dataset_test_40 = test_40.values
X_test_40 = dataset_test_40[:,0:9]
print(X_test_40)

y_test_40= dataset_test_40[:,9]
print(y_test_40)

[[ 5.9940000e-01  2.2963700e-01 -2.8239780e+00 ... -2.4300000e-02
  -3.6200000e-04  2.4489600e-01]
 [ 7.3290000e-01 -9.8103230e+00 -7.1901720e+00 ...  2.5711800e-01
  -6.0500000e-04 -7.1654000e-02]
 [ 2.1705000e-01 -3.7397320e+00  4.0531970e+00 ...  1.9575700e-01
  -1.3330000e-03 -8.8163000e-02]
 ...
 [ 2.5000000e-01  1.0901083e+01  7.0995010e+00 ...  1.2544300e-01
  -4.1500000e-04  2.2458200e-01]
 [ 8.2825000e-01 -5.1418580e+00  1.8279100e-01 ...  1.5684400e-01
  -7.5200000e-04  2.0937300e-01]
 [ 3.8300000e-02 -1.1228797e+01  1.1330514e+01 ...  3.3639000e-02
  -3.0800000e-04  8.7114000e-02]]
[1. 0. 3. ... 2. 0. 1.]


### Predictions with 10Hz Trained Model

In [60]:
import numpy as np

In [61]:
predictions_10 = rf_10.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 10Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 10Hz: 1.697 degrees.
Accuracy: 98.303 %.


In [62]:
predictions_15 = rf_10.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 10Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 10Hz: 1.536 degrees.
Accuracy: 98.464 %.


In [63]:
predictions_20 = rf_10.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 10Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 10Hz: 1.515 degrees.
Accuracy: 98.485 %.


In [64]:
predictions_25 = rf_10.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 10Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 10Hz: 1.507 degrees.
Accuracy: 98.493 %.


In [65]:
predictions_30 = rf_10.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 10Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 10Hz: 1.528 degrees.
Accuracy: 98.472 %.


In [66]:
predictions_35 = rf_10.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 10Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 10Hz: 1.55 degrees.
Accuracy: 98.45 %.


In [67]:
predictions_40 = rf_10.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 10Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 10Hz: 1.541 degrees.
Accuracy: 98.459 %.


### Predictions with 15Hz model

In [68]:
predictions_10 = rf_15.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 15Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 15Hz: 1.385 degrees.
Accuracy: 98.615 %.


In [69]:
predictions_15 = rf_15.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 15Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 15Hz: 1.241 degrees.
Accuracy: 98.759 %.


In [70]:
predictions_20 = rf_15.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 15Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 15Hz: 1.231 degrees.
Accuracy: 98.769 %.


In [71]:
predictions_25 = rf_15.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 15Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 15Hz: 1.225 degrees.
Accuracy: 98.775 %.


In [72]:
predictions_30 = rf_15.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 15Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 15Hz: 1.205 degrees.
Accuracy: 98.795 %.


In [73]:
predictions_35 = rf_15.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 15Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 15Hz: 1.299 degrees.
Accuracy: 98.701 %.


In [74]:
predictions_40 = rf_15.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 15Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 15Hz: 1.296 degrees.
Accuracy: 98.704 %.


### Predictions with 20Hz model

In [75]:
predictions_10 = rf_20.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 20Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 20Hz: 1.348 degrees.
Accuracy: 98.652 %.


In [76]:
predictions_15 = rf_20.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 20Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 20Hz: 1.29 degrees.
Accuracy: 98.71 %.


In [77]:
predictions_20 = rf_20.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 20Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 20Hz: 1.124 degrees.
Accuracy: 98.876 %.


In [78]:
predictions_25 = rf_20.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 20Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 20Hz: 1.123 degrees.
Accuracy: 98.877 %.


In [79]:
predictions_30 = rf_20.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 20Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 20Hz: 1.2 degrees.
Accuracy: 98.8 %.


In [80]:
predictions_35 = rf_20.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 20Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 20Hz: 1.143 degrees.
Accuracy: 98.857 %.


In [81]:
predictions_40 = rf_20.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 20Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 20Hz: 1.19 degrees.
Accuracy: 98.81 %.


### Predictions with 25Hz model

In [82]:
predictions_10 = rf_25.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 25Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 25Hz: 1.428 degrees.
Accuracy: 98.572 %.


In [83]:
predictions_15 = rf_25.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 25Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 25Hz: 1.312 degrees.
Accuracy: 98.688 %.


In [84]:
predictions_20 = rf_25.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 25Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 25Hz: 1.211 degrees.
Accuracy: 98.789 %.


In [85]:
predictions_25 = rf_25.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 25Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 25Hz: 1.025 degrees.
Accuracy: 98.975 %.


In [86]:
predictions_30 = rf_25.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 25Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 25Hz: 1.037 degrees.
Accuracy: 98.963 %.


In [87]:
predictions_35 = rf_25.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 25Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 25Hz: 0.976 degrees.
Accuracy: 99.024 %.


In [88]:
predictions_40 = rf_25.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 25Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 25Hz: 0.995 degrees.
Accuracy: 99.005 %.


### Predictions with 30Hz model

In [89]:
predictions_10 = rf_30.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 30Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 30Hz: 1.463 degrees.
Accuracy: 98.537 %.


In [90]:
predictions_15 = rf_30.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 30Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 30Hz: 1.354 degrees.
Accuracy: 98.646 %.


In [91]:
predictions_20 = rf_30.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 30Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 30Hz: 1.153 degrees.
Accuracy: 98.847 %.


In [92]:
predictions_25 = rf_30.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 30Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 30Hz: 0.932 degrees.
Accuracy: 99.068 %.


In [93]:
predictions_30 = rf_30.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 30Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 30Hz: 0.905 degrees.
Accuracy: 99.095 %.


In [94]:
predictions_35 = rf_30.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 30Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 30Hz: 0.853 degrees.
Accuracy: 99.147 %.


In [95]:
predictions_40 = rf_30.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 30Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 30Hz: 0.775 degrees.
Accuracy: 99.225 %.


### Testing with 35Hz model

In [96]:
predictions_10 = rf_35.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 35Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 35Hz: 1.41 degrees.
Accuracy: 98.59 %.


In [97]:
predictions_15 = rf_35.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 35Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 35Hz: 1.345 degrees.
Accuracy: 98.655 %.


In [98]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 35Hz: 1.202 degrees.
Accuracy: 98.798 %.


In [99]:
predictions_25 = rf_35.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 35Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 35Hz: 0.996 degrees.
Accuracy: 99.004 %.


In [100]:
predictions_30 = rf_35.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 35Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 35Hz: 1.02 degrees.
Accuracy: 98.98 %.


In [101]:
predictions_35 = rf_35.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 35Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 35Hz: 0.843 degrees.
Accuracy: 99.157 %.


In [102]:
predictions_40 = rf_35.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 35Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 35Hz: 0.933 degrees.
Accuracy: 99.067 %.


### Training with 40Hz model

In [103]:
predictions_10 = rf_35.predict(X_test_10)
errors_10 = abs(predictions_10 - y_test_10)
print('Mean Absolute Error 10Hz with 35Hz:', round(np.mean(errors_10), 3), 'degrees.')

accuracy = 100 - np.mean(errors_10)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 10Hz with 35Hz: 1.41 degrees.
Accuracy: 98.59 %.


In [104]:
predictions_15 = rf_35.predict(X_test_15)
errors_15 = abs(predictions_15 - y_test_15)
print('Mean Absolute Error 15Hz with 35Hz:', round(np.mean(errors_15), 3), 'degrees.')

accuracy = 100 - np.mean(errors_15)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 15Hz with 35Hz: 1.345 degrees.
Accuracy: 98.655 %.


In [105]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 35Hz: 1.202 degrees.
Accuracy: 98.798 %.


In [106]:
predictions_20 = rf_35.predict(X_test_20)
errors_20 = abs(predictions_20 - y_test_20)
print('Mean Absolute Error 20Hz with 35Hz:', round(np.mean(errors_20), 3), 'degrees.')

accuracy = 100 - np.mean(errors_20)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 20Hz with 35Hz: 1.202 degrees.
Accuracy: 98.798 %.


In [107]:
predictions_25 = rf_35.predict(X_test_25)
errors_25 = abs(predictions_25 - y_test_25)
print('Mean Absolute Error 25Hz with 35Hz:', round(np.mean(errors_25), 3), 'degrees.')

accuracy = 100 - np.mean(errors_25)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 25Hz with 35Hz: 0.996 degrees.
Accuracy: 99.004 %.


In [108]:
predictions_30 = rf_35.predict(X_test_30)
errors_30 = abs(predictions_30 - y_test_30)
print('Mean Absolute Error 30Hz with 35Hz:', round(np.mean(errors_30), 3), 'degrees.')

accuracy = 100 - np.mean(errors_30)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 30Hz with 35Hz: 1.02 degrees.
Accuracy: 98.98 %.


In [109]:
predictions_35 = rf_35.predict(X_test_35)
errors_35 = abs(predictions_35 - y_test_35)
print('Mean Absolute Error 35Hz with 35Hz:', round(np.mean(errors_35), 3), 'degrees.')

accuracy = 100 - np.mean(errors_35)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 35Hz with 35Hz: 0.843 degrees.
Accuracy: 99.157 %.


In [110]:
predictions_40 = rf_35.predict(X_test_40)
errors_40 = abs(predictions_40 - y_test_40)
print('Mean Absolute Error 40Hz with 35Hz:', round(np.mean(errors_40), 3), 'degrees.')

accuracy = 100 - np.mean(errors_40)
print('Accuracy:', round(accuracy, 3), '%.')

Mean Absolute Error 40Hz with 35Hz: 0.933 degrees.
Accuracy: 99.067 %.
